import os
import re
import pandas as pd
import streamlit as st

DEFAULT_CSV = os.path.join("data", "probate_records.csv")

st.set_page_config(page_title="Probate PDF Extracts", layout="wide")
st.title("Probate Records Dashboard")

csv_path = st.sidebar.text_input("CSV path", DEFAULT_CSV)
reload = st.sidebar.button("Reload CSV")

def _get_mtime(path: str) -> float:
    try:
        return os.path.getmtime(path)
    except Exception:
        return 0.0


@st.cache_data(show_spinner=False)
def load_data(path: str, mtime: float):
    if not os.path.exists(path):
        return pd.DataFrame()
    df = pd.read_csv(path)
    # Parse dates if present
    for col in ("run_at", "decedent_dod", "entry_date"):
        if col in df.columns:
            try:
                df[col] = pd.to_datetime(df[col], errors="coerce")
            except Exception:
                pass
    # Normalize phone/strings
    for col in ("first_page_phone", "first_page_email", "file_number", "docket", "county", "case_type"):
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip()
    # Create a simple unique id
    if {"file_number", "docket"}.issubset(df.columns):
        df["record_id"] = df["file_number"].fillna("") + "|" + df["docket"].fillna("")
    elif "file_number" in df.columns:
        df["record_id"] = df["file_number"].fillna("")
    elif "source_file" in df.columns:
        df["record_id"] = df["source_file"].fillna("")
    else:
        df["record_id"] = df.index.astype(str)
    return df

if reload:
    load_data.clear()

csv_mtime = _get_mtime(csv_path)
df = load_data(csv_path, csv_mtime)

if df.empty:
    st.info("No data found. Run the extractor to populate the CSV first.")
    st.stop()

with st.sidebar:
    counties = sorted([c for c in df.get("county", pd.Series([])).dropna().unique() if c])
    county_choice = st.selectbox("County", ["All"] + counties, index=0)
    name_query = st.text_input("Search Decedent/Contact Name")
    hide_apartments = st.checkbox("Hide apartments (Apt/Unit/Suite/#)", value=False)

fdf = df.copy()
if county_choice and county_choice != "All":
    fdf = fdf[fdf["county"] == county_choice]
if name_query:
    nq = name_query.strip().lower()
    cols = [c for c in ["decedent_name", "first_page_name"] if c in fdf.columns]
    if cols:
        mask = False
        for c in cols:
            mask = mask | fdf[c].fillna("").str.lower().str.contains(nq)
        fdf = fdf[mask]

# Optional filter: hide addresses that look like apartments/units
def _looks_like_apartment(s: str) -> bool:
    if not s:
        return False
    s = str(s)
    low = s.lower()
    # Common unit markers
    if re.search(r"\b(apt|apartment|unit|suite|ste|fl|floor)\b", low):
        return True
    # Inline '#' unit notation like '# 4J'
    if re.search(r"(^|\s)#\s*[a-z0-9\-]+\b", low):
        return True
    return False

if hide_apartments and "first_page_address_lines" in fdf.columns:
    fdf = fdf[~fdf["first_page_address_lines"].fillna("").map(_looks_like_apartment)]

st.subheader("Overview")
left, mid, right = st.columns(3)
with left:
    st.metric("Total Records", len(df))
with mid:
    st.metric("Filtered Records", len(fdf))
with right:
    st.metric("Unique File Numbers", fdf.get("file_number", pd.Series([])).nunique())

st.subheader("Records Table")
display_cols = [
    c for c in [
        "county",
        "file_number",
        "decedent_name",
        "decedent_dod",   # DOD
        "first_page_phone",
        "first_page_address_lines",
        "first_page_email",
        "source_file",
    ] if c in fdf.columns
]
# Build a safe sort key list limited to visible columns
sort_candidates = ["run_at", "county", "file_number"]
sort_by = [c for c in sort_candidates if c in fdf.columns and c in display_cols]
asc_map = {"run_at": False, "county": True, "file_number": True}
asc_flags = [asc_map[c] for c in sort_by]

df_view = fdf[display_cols] if display_cols else fdf
if sort_by:
    try:
        df_view = df_view.sort_values(by=sort_by, ascending=asc_flags)
    except Exception:
        pass
st.dataframe(df_view, height=520, use_container_width=True)

st.subheader("Breakdown")
if "county" in fdf.columns and not fdf.empty:
    st.bar_chart(fdf["county"].value_counts().sort_values(ascending=False))

st.caption("Data source: CSV generated by pdf_data_extractor.py")
